Fix test release 015
jasp-stats/jaspEquivalenceTTests pull request #53
Opened 2021-09-14 09:30 UTC by Jillderon

Fixes #1306: https://github.com/jasp-stats/jasp-test-release/issues/1306

2021-09-14 14:07 UTC, TimKDJ requested changes
This does not fix the linked issue; the plots are still re-made -- you need to look at `.equivalencePlotInd()` (and possibly other plotting functions)?

2021-09-14 14:09 UTC, TimKDJ commented on R/equivalencebayesianpairedsamplesttest.R
> +  if(options$descriptives && is.null(jaspResults[["equivalenceBayesianDescriptivesTable"]]))
Actually [that function already does a null check](https://github.com/jasp-stats/jaspEquivalenceTTests/blob/986d23fbc80d6dea7f1403097fce006582fb0ae1/R/equivalencebayesianpairedsamplesttest.R#L220), so this addition is not necessary

2022-04-20 16:05 UTC, Kucharssim commented
@Jillderon do you want to work this in 0.16.3?

2024-11-08 13:28 UTC, FBartos commented
this is obsolete now

2024-11-08 13:28 UTC, closed without merging