Unit Tests
jasp-stats/jaspEquivalenceTTests pull request #8
Opened 2020-12-01 21:41 UTC by Jillderon

I added the unit tests for the equivalence module

2020-12-02 11:17 UTC, vandenman requested changes
- Please delete `.travis.yml`
- Please add `jaspTTests` to the DESCRIPTION file, like [here](https://github.com/jasp-stats/jaspAnova/blob/master/DESCRIPTION), so both under `Imports` and under `Remotes`.

2020-12-02 11:17 UTC, vandenman commented on inst/qml/EquivalencePairedSamplesTTest.qml
> +              DoubleField { name: "lowerbound"; label: qsTr("from")	; max: upperbound.value; defaultValue: -0.05; id: lowerbound; negativeValues: true; enabled: region.checked; inclusive: JASP.None}
This could be a separate QML element, rather than copying it 6 times.

2020-12-02 11:17 UTC, vandenman commented on R/commonequivalencefunctions.R
> +## From here on function are from the T-Test module
this can be deleted right?

2020-12-07 10:35 UTC, vandenman commented
use `jaspTTest:::.ttestReadData` (three `:::`) to import the read data function (that's why the unit tests fail).

2020-12-08 10:37 UTC, TimKDJ commented
Probably good to export the functions from jaspTTests (or copy them) that are used here.
Otherwise we won't know in jaspTTests and might accidentally break stuff

2020-12-08 10:41 UTC, vandenman commented
Actually, copying the function might be better because the function is rather specific and depends on the names in `options`.

2020-12-14 08:07 UTC, vandenman commented
Three plots seem to fail. I can replicate this locally although I'm not sure what causes the differences. If you run `manageTestPlots()` you can update the figures.

2020-12-14 08:24 UTC, Jillderon commented
Weird, I did not run into problems locally as well. I’ll manageTestPlots
again yes!

Op ma 14 dec. 2020 om 09:07 schreef Don van den Bergh <
notifications@github.com>

> Three plots seem to fail. I can replicate this locally although I'm not
> sure what causes the differences. If you run manageTestPlots() you can
> update the figures.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jasp-stats/jaspEquivalenceTTests/pull/8#issuecomment-744257871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFQ5IRMPAC7HREDVWSERWQTSUXBT7ANCNFSM4UJS532A>
> .
>

2021-04-21 09:30 UTC, vandenman approved these changes

2021-04-21 09:31 UTC, merged